add docker-compose files and README
dojot/docker-compose-locust pull request #1
Opened 2021-08-04 11:13 UTC by ctossato

2021-08-06 11:15 UTC, danielapetito commented on docker-compose-master.yml
> +      DOJOT_URL: "http://127.0.0.1:8000"
não seria legal usar localhost ?

2021-08-06 11:15 UTC, danielapetito commented on docker-compose-master.yml
> +      DOJOT_MQTT_HOST: "127.0.0.1"
não seria legal usar localhost ?

2021-08-06 11:16 UTC, danielapetito commented on docker-compose-slave.yml
> +      DOJOT_URL: "http://127.0.0.1:8000"
não seria legal usar localhost ?

2021-08-06 11:16 UTC, danielapetito commented on docker-compose-slave.yml
> +      DOJOT_MQTT_HOST: "127.0.0.1"
não seria legal usar localhost ?

2021-08-06 11:19 UTC, danielapetito commented on docker-compose-generate_certs.yml
> +      DOJOT_URL: "http://127.0.0.1:8000"
não seria legal usar localhost ?

2021-08-06 11:19 UTC, danielapetito commented on docker-compose-generate_certs.yml
> +      DOJOT_MQTT_HOST: "127.0.0.1"
não seria legal usar localhost ?

2021-08-09 18:19 UTC, danielapetito approved these changes

2021-08-09 18:39 UTC, marianoleonardo requested changes

2021-08-09 18:39 UTC, marianoleonardo commented on README.md
> +For instructions on how to configure and how to it works, please check the [documentation](https://github.com/dojot/dojot/tree/master/connector/mqtt/locust/README.md)
I think you should change this link to `https://dojotdocs.readthedocs.io/en/latest/load-testing-dojot-platform.html` or simply add it.

The README.MD that you linked here its almost the same as this README.MD.

2021-09-17 18:38 UTC, ctossato commented on README.md
> +For instructions on how to configure and how to it works, please check the [documentation](https://github.com/dojot/dojot/tree/master/connector/mqtt/locust/README.md)
Leo, penso que esse link da documentação tem algumas informações a mais. Mas o tutorial também é legal. que tal assim:

For instructions on how to configure and how to it works, please check the [documentation](https://github.com/dojot/dojot/tree/master/connector/mqtt/locust/README.md) or follow the [tutorial](https://dojotdocs.readthedocs.io/en/latest/load-testing-dojot-platform.html).

2021-09-17 20:26 UTC, marianoleonardo commented on README.md
> +For instructions on how to configure and how to it works, please check the [documentation](https://github.com/dojot/dojot/tree/master/connector/mqtt/locust/README.md)
Ótima ideia Carlos!

2021-10-04 18:02 UTC, danielapetito submitted a review, later dismissed

2021-10-05 13:20 UTC, marianoleonardo submitted a review, later dismissed

2021-10-05 16:47 UTC, marianoleonardo approved these changes

2021-10-05 16:54 UTC, merged